### ISSUE TITLE
Documentation broken

### ISSUE THREAD

**Issue by ritesh-pandey** [gilbitron/carouFredSel#31]
http://docs.dev7studios.com/jquery-plugins/caroufredsel-advanced
Custom events section.

HTML source code is visible and not the actual documentation. Looks like there is some problem in some plugin which translates HTML to tablized form.

**Comment by dotmagic** [comment]
They redirect the url to her paid version of the wordpress plugin. That really sucks.
Please upload the docs at least on github.

**Comment by gilbitron** [comment]
I've just updated the docs to sort the issue http://docs.dev7studios.com/jquery-plugins/caroufredsel
